### PR TITLE
Gamygdala action executors

### PR DESCRIPTION
**Pull request by wouterposdijk**

### CODE REVIEW

**Comment by tomh5905** [comment]
I get a test failure when I run it on my machine. testCollectCoins failed.

**Comment by wouterposdijk** [comment]
Yes, that test failure is also because Gamygdala cannot be resolved somehow. I'm trying to fix this now.

**Comment by wouterposdijk** [comment]
The current build failures are simply because travis cannot execute the blocks world environment. If any osx/windows/linux pc with a graphical interface would try this it would work, so the pull request can be merged.

**Comment by tomh5905** [comment]
I tried it on my machine but I do still get a build failure on the same test. Do you know what this problem could be?

**Comment by wouterposdijk** [comment]
I think you did not update the goal-gamygdala version. You can do this by deleting it from your local maven repos and reimporting your maven project.

**Comment by tomh5905** [comment]
Nice, successful ;)

**Comment by svenpopping** [comment]
Maven build successfull

**Pull request merged**
